global using MongoDB.Bson;
global using MongoDB.Bson.Serialization.Attributes;
global using System.ComponentModel.DataAnnotations;
// global using api.DTOs;
global using api.Interfaces;
global using api.Models;
global using api.Settings;
global using Microsoft.AspNetCore.Authorization;
global using MongoDB.Driver;
global using api.Controllers.Helpers;
global using System.Security.Cryptography;
global using System.Text;
global using Microsoft.AspNetCore.Mvc;
global using System.Security.Claims;